# Generated by Django 4.2.1 on 2023-06-18 09:18

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(upload_to=API.models.saveImg),
        ),
    ]
